
#@author :abdelhamid.belgacem

swagger: '2.0'
info:
  version: '1.0'
  title: 'SMS-feeds'
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /feeds:
    GET:
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Feed'
      responses:
        '201':
          description: Get All Feeds  
          headers:
            location:
              schema:
                type: string
          content:
            schema:
              $ref: '#/definitions/Feed'
        '406':
          description: Not acceptable, ie, Feed's short name already exists
          schema:
            oneOf:
              - $ref: '#/definitions/ErrorList'
              - type: string
      x-amazon-apigateway-integration:
        uri:
          arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:698181446882:function:${stageVariables.getFeedsLambda}/invocations
        passthroughBehavior: when_no_match
        httpMethod: GET
        type: aws_proxy

definitions:
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      additionalProperties:
        type: string
  ErrorList:
    type: array
    items:
      $ref: '#/definitions/Error'

  Link:
    type: object
    properties:
      href: 
        type: string
      linkBuilder:
        type: string
      linkBuilderParameters:
        type: object
        additionalProperties:
          type: string

  Feed:
    type: object
    properties:
      _links:
        type: object
        properties:
          self:
            $ref: '#/definitions/Link'
      name: 
        type: string
      shortName:
        type: string
      
