
#@author :abdelhamid.belgacem


AWSTemplateFormatVersion: '2017-09-09'
Transform: AWS::Serverless-2016-10-31
Description: profiles management system
Parameters:
  DynamoDBStack:
    Type: String
  ApiBasePath:
    Type: String
    Default: v1

Resources:        
  postprofilesLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.post
      Runtime: nodejs6.10
      Timeout: 1
      MemorySize: 128
      CodeUri: .
      Policies: 
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          profiles_TABLE_NAME:
            Fn::ImportValue:
              !Sub ${DynamoDBStack}-profilesDynamoDBTable
      Events:
        postprofilesEvent:
          Type: Api
          Properties:
            Path: /profiles
            Method: post
            RestApiId : !Ref profilesApi
            
           


           
            
            #UPDATE PROFILES DATA
            
            
            
            
            
            Properties:
      Handler: index.patch
      Runtime: nodejs6.10
      Timeout: 1
      MemorySize: 128
      CodeUri: .
      Policies: 
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          profiles_TABLE_NAME:
            Fn::ImportValue:
              !Sub ${DynamoDBStack}-profilesDynamoDBTable
      Events:
        postprofilesEvent:
          Type: Api
          Properties:
            Path: /profiles/{id}
            Method: patch
            RestApiId : !Ref profilesApi

  profilesApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./profiles-api-swagger.yml
      StageName: deployed
      Variables:
        postprofilesLambda: !Ref postprofilesLambda

  profilesDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties: 
    
    #arn:aws:lambda:eu-central-1:698181446882:function:postprofiles
        CertificateArn: arn:aws:lambda:eu-central-1:698181446882:certificate/2ea697a4-582d-4a17-9db8-189a98bc1121
      DomainName: 
        Fn::Join: [
          ".",
          [
            !Ref "AWS::StackName",
            "profiles.ifsalpha.com"
          ]
        ]

  profilesBasePathMapping:
      Type: AWS::ApiGateway::BasePathMapping
      DependsOn:
        - profilesApideployedStage
        - profilesDomainName
      Properties:
        DomainName: !Ref profilesDomainName
        BasePath: !Sub ${ApiBasePath}
        RestApiId: !Ref profilesApi
        Stage: deployed

  profilesUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
        - profilesApideployedStage
    Properties:
      ApiStages:
        - ApiId: !Ref profilesApi
          Stage: deployed
      Throttle:
        BurstLimit: 500
        RateLimit: 50
      UsagePlanName:
        Fn::Join: [
            "-",
            [
              !Ref "AWS::StackName",
              "usage",
              "plan"
            ]
          ]
