
#@author :abdelhamid.belgacem

AWSTemplateFormatVersion: '2017-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Profiles management system
Parameters:
  DynamoDBStack:
    Type: String
  ApiBasePath:
    Type: String
    Default: v1

Resources:        
  getProfilesLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      Runtime: nodejs6.10
      Timeout: 1
      MemorySize: 128
      CodeUri: .
      Policies: 
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          Profiles_TABLE_NAME:
            Fn::ImportValue:
              !Sub ${DynamoDBStack}-ProfilesDynamoDBTable
      Events:
        getProfilesEvent:
          Type: Api
          Properties:
            Path: /Profiles
            Method: post
            RestApiId : !Ref ProfilesApi

  ProfilesApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./profiles-api-swagger.yml
      StageName: deployed
      Variables:
        getProfilesLambda: !Ref getProfilesLambda

  ProfilesDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties: 
    
    #arn:aws:lambda:eu-central-1:698181446882:function:GetProfiles
        CertificateArn: arn:aws:lambda:eu-central-1:698181446882:certificate/2ea697a4-582d-4a17-9db8-189a98bc1121
      DomainName: 
        Fn::Join: [
          ".",
          [
            !Ref "AWS::StackName",
            "profiless.ifsalpha.com"
          ]
        ]

  ProfilesBasePathMapping:
      Type: AWS::ApiGateway::BasePathMapping
      DependsOn:
        - ProfilesApideployedStage
        - ProfilesDomainName
      Properties:
        DomainName: !Ref ProfilesDomainName
        BasePath: !Sub ${ApiBasePath}
        RestApiId: !Ref ProfilesApi
        Stage: deployed

  ProfilesUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
        - ProfilesApideployedStage
    Properties:
      ApiStages:
        - ApiId: !Ref ProfilesApi
          Stage: deployed
      Throttle:
        BurstLimit: 500
        RateLimit: 50
      UsagePlanName:
        Fn::Join: [
            "-",
            [
              !Ref "AWS::StackName",
              "usage",
              "plan"
            ]
          ]